title = 'Canadian Finance Options'
baseURL = 'https://www.financeoptions.ca/'
languageCode = 'en-us'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Ananke"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  #[languages.fr]
  #  title = "Ananke Fr"
  #  weight = 2
  #  contentDir = "content/fr"

[params]
  site_logo = "images/logo.png"
  description = "Personal Money Management"
  
